name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install semantic-release
        run: pnpm add -D conventional-changelog-conventionalcommits semantic-release @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SEMANTIC_TOKEN  }}
        run: pnpm exec semantic-release
